/**
 * @author  AliReza Joodi
 * @see     https://github.com/AliRezaJoodi
 */
 
#ifndef AJ_BUS_TYPE_INCLUDED
#define AJ_BUS_TYPE_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

#include <stm32f4xx.h>

//********************************************************
typedef enum {
	AJ_BUS_CLOCK_DISABLE = 0U,
	AJ_BUS_CLOCK_ENABLE  = 1U
} aj_bus_clock_state_t;

//********************************************************
typedef enum {
	#if defined(RCC_AHB1ENR_GPIOAEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOA = RCC_AHB1ENR_GPIOAEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOBEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOB = RCC_AHB1ENR_GPIOBEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOCEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOC = RCC_AHB1ENR_GPIOCEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIODEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOD = RCC_AHB1ENR_GPIODEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOEEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOE = RCC_AHB1ENR_GPIOEEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOFEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOF = RCC_AHB1ENR_GPIOFEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOGEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOG = RCC_AHB1ENR_GPIOGEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOHEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOH = RCC_AHB1ENR_GPIOHEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOIEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOI = RCC_AHB1ENR_GPIOIEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOJEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOJ = RCC_AHB1ENR_GPIOJEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_GPIOKEN_Msk)
		AJ_BUS_AHB1_CLOCK_GPIOK = RCC_AHB1ENR_GPIOKEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_CRCEN_Msk)
		AJ_BUS_AHB1_CLOCK_CRC = RCC_AHB1ENR_CRCEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_BKPSRAMEN_Msk)
		AJ_BUS_AHB1_CLOCK_BKPSRAM = RCC_AHB1ENR_BKPSRAMEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_CCMDATARAMEN_Msk)
		AJ_BUS_AHB1_CLOCK_CCMDATARAM = RCC_AHB1ENR_CCMDATARAMEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_DMA1EN_Msk)
		AJ_BUS_AHB1_CLOCK_DMA1 = RCC_AHB1ENR_DMA1EN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_DMA2EN_Msk)
		AJ_BUS_AHB1_CLOCK_DMA2 = RCC_AHB1ENR_DMA2EN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_DMA2DEN_Msk)
		AJ_BUS_AHB1_CLOCK_DMA2D = RCC_AHB1ENR_DMA2DEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_ETHMACEN_Msk)
		AJ_BUS_AHB1_CLOCK_ETHMAC = RCC_AHB1ENR_ETHMACEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_ETHMACTXEN_Msk)
		AJ_BUS_AHB1_CLOCK_ETHMACTX = RCC_AHB1ENR_ETHMACTXEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_ETHMACRXEN_Msk)
		AJ_BUS_AHB1_CLOCK_ETHMACRX = RCC_AHB1ENR_ETHMACRXEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_ETHMACPTPEN_Msk)
		AJ_BUS_AHB1_CLOCK_ETHMACPTP = RCC_AHB1ENR_ETHMACPTPEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_OTGHSEN_Msk)
		AJ_BUS_AHB1_CLOCK_OTGHS = RCC_AHB1ENR_OTGHSEN_Msk,
	#endif

	#if defined(RCC_AHB1ENR_OTGHSULPIEN_Msk)
		AJ_BUS_AHB1_CLOCK_OTGHSULPI = RCC_AHB1ENR_OTGHSULPIEN_Msk,
	#endif

	AJ_BUS_AHB1_CLOCK_ALL = 0xFFFFFFFFU
} aj_bus_ahb1_clock_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_AHB1RSTR_GPIOARST_Msk)
		AJ_BUS_AHB1_RESET_GPIOA = RCC_AHB1RSTR_GPIOARST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOBRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOB = RCC_AHB1RSTR_GPIOBRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOCRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOC = RCC_AHB1RSTR_GPIOCRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIODRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOD = RCC_AHB1RSTR_GPIODRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOERST_Msk)
		AJ_BUS_AHB1_RESET_GPIOE = RCC_AHB1RSTR_GPIOERST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOFRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOF = RCC_AHB1RSTR_GPIOFRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOGRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOG = RCC_AHB1RSTR_GPIOGRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOHRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOH = RCC_AHB1RSTR_GPIOHRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOIRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOI = RCC_AHB1RSTR_GPIOIRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOJRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOJ = RCC_AHB1RSTR_GPIOJRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_GPIOKRST_Msk)
		AJ_BUS_AHB1_RESET_GPIOK = RCC_AHB1RSTR_GPIOKRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_CRCRST_Msk)
		AJ_BUS_AHB1_RESET_CRC = RCC_AHB1RSTR_CRCRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_DMA1RST_Msk)
		AJ_BUS_AHB1_RESET_DMA1 = RCC_AHB1RSTR_DMA1RST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_DMA2RST_Msk)
		AJ_BUS_AHB1_RESET_DMA2 = RCC_AHB1RSTR_DMA2RST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_DMA2DRST_Msk)
		AJ_BUS_AHB1_RESET_DMA2D = RCC_AHB1RSTR_DMA2DRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_ETHMACRST_Msk)
		AJ_BUS_AHB1_RESET_ETHMAC = RCC_AHB1RSTR_ETHMACRST_Msk,
	#endif

	#if defined(RCC_AHB1RSTR_OTGHRST_Msk)
		AJ_BUS_AHB1_RESET_OTGHS = RCC_AHB1RSTR_OTGHRST_Msk,
	#endif

	AJ_BUS_AHB1_RESET_ALL = 0xFFFFFFFFU
} aj_bus_ahb1_reset_mask_t;

//********************************************************
/* LP: Low Power */
typedef enum {
	#if defined(RCC_AHB1LPENR_GPIOALPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOA = RCC_AHB1LPENR_GPIOALPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOBLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOB = RCC_AHB1LPENR_GPIOBLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOCLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOC = RCC_AHB1LPENR_GPIOCLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIODLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOD = RCC_AHB1LPENR_GPIODLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOELPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOE = RCC_AHB1LPENR_GPIOELPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOFLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOF = RCC_AHB1LPENR_GPIOFLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOGLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOG = RCC_AHB1LPENR_GPIOGLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOHLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOH = RCC_AHB1LPENR_GPIOHLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOILPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOI = RCC_AHB1LPENR_GPIOILPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOJLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOJ = RCC_AHB1LPENR_GPIOJLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_GPIOKLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_GPIOK = RCC_AHB1LPENR_GPIOKLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_CRCLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_CRC = RCC_AHB1LPENR_CRCLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_FLITFLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_FLITF = RCC_AHB1LPENR_FLITFLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_SRAM1LPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_SRAM1 = RCC_AHB1LPENR_SRAM1LPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_SRAM2LPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_SRAM2 = RCC_AHB1LPENR_SRAM2LPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_BKPSRAMLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_BKPSRAM = RCC_AHB1LPENR_BKPSRAMLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_SRAM3LPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_SRAM3 = RCC_AHB1LPENR_SRAM3LPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_DMA1LPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_DMA1 = RCC_AHB1LPENR_DMA1LPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_DMA2LPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_DMA2 = RCC_AHB1LPENR_DMA2LPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_DMA2DLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_DMA2D = RCC_AHB1LPENR_DMA2DLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_ETHMACLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_ETHMAC = RCC_AHB1LPENR_ETHMACLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_ETHMACTXLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_ETHMACTX = RCC_AHB1LPENR_ETHMACTXLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_ETHMACRXLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_ETHMACRX = RCC_AHB1LPENR_ETHMACRXLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_ETHMACPTPLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_ETHMACPTP = RCC_AHB1LPENR_ETHMACPTPLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_OTGHSLPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_OTGHS = RCC_AHB1LPENR_OTGHSLPEN_Msk,
	#endif

	#if defined(RCC_AHB1LPENR_OTGHSULPILPEN_Msk)
		AJ_BUS_AHB1_CLOCK_LP_OTGHSULPI = RCC_AHB1LPENR_OTGHSULPILPEN_Msk,
	#endif

	AJ_BUS_AHB1_CLOCK_LP_ALL = 0xFFFFFFFFU
} aj_bus_ahb1_clock_lp_mask_t;


#if defined(RCC_AHB2_SUPPORT)
//********************************************************
typedef enum {
	#if defined(RCC_AHB2ENR_DCMIEN_Msk)
		AJ_BUS_AHB2_CLOCK_DCMI = RCC_AHB2ENR_DCMIEN_Msk,
	#endif

	#if defined(RCC_AHB2ENR_CRYPEN_Msk)
		AJ_BUS_AHB2_CLOCK_CRYP = RCC_AHB2ENR_CRYPEN_Msk,
	#endif

	#if defined(RCC_AHB2ENR_AESEN_Msk)
		AJ_BUS_AHB2_CLOCK_AES = RCC_AHB2ENR_AESEN_Msk,
	#endif

	#if defined(RCC_AHB2ENR_HASHEN_Msk)
		AJ_BUS_AHB2_CLOCK_HASH = RCC_AHB2ENR_HASHEN_Msk,
	#endif

	#if defined(RCC_AHB2ENR_RNGEN_Msk)
		AJ_BUS_AHB2_CLOCK_RNG = RCC_AHB2ENR_RNGEN_Msk,
	#endif

	#if defined(RCC_AHB2ENR_OTGFSEN_Msk)
		AJ_BUS_AHB2_CLOCK_OTGFS = RCC_AHB2ENR_OTGFSEN_Msk,
	#endif

	AJ_BUS_AHB2_CLOCK_ALL = 0xFFFFFFFFU
} aj_bus_ahb2_clock_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_AHB2RSTR_DCMIRST_Msk)
		AJ_BUS_AHB2_RESET_DCMI = RCC_AHB2RSTR_DCMIRST_Msk,
	#endif

	#if defined(RCC_AHB2RSTR_CRYPRST_Msk)
		AJ_BUS_AHB2_RESET_CRYP = RCC_AHB2RSTR_CRYPRST_Msk,
	#endif

	#if defined(RCC_AHB2RSTR_AESRST_Msk)
		AJ_BUS_AHB2_RESET_AES = RCC_AHB2RSTR_AESRST_Msk,
	#endif

	#if defined(RCC_AHB2RSTR_HASHRST_Msk)
		AJ_BUS_AHB2_RESET_HASH = RCC_AHB2RSTR_HASHRST_Msk,
	#endif

	#if defined(RCC_AHB2RSTR_RNGRST_Msk)
		AJ_BUS_AHB2_RESET_RNG = RCC_AHB2RSTR_RNGRST_Msk,
	#endif

	#if defined(RCC_AHB2RSTR_OTGFSRST_Msk)
		AJ_BUS_AHB2_RESET_OTGFS = RCC_AHB2RSTR_OTGFSRST_Msk,
	#endif

	AJ_BUS_AHB2_RESET_ALL = 0xFFFFFFFFU
} aj_bus_ahb2_reset_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_AHB2LPENR_DCMILPEN_Msk)
		AJ_BUS_AHB2_CLOCK_LP_DCMI = RCC_AHB2LPENR_DCMILPEN_Msk,
	#endif

	#if defined(RCC_AHB2LPENR_CRYPLPEN_Msk)
		AJ_BUS_AHB2_CLOCK_LP_CRYP = RCC_AHB2LPENR_CRYPLPEN_Msk,
	#endif

	#if defined(RCC_AHB2LPENR_AESLPEN_Msk)
		AJ_BUS_AHB2_CLOCK_LP_AES = RCC_AHB2LPENR_AESLPEN_Msk,
	#endif

	#if defined(RCC_AHB2LPENR_HASHLPEN_Msk)
		AJ_BUS_AHB2_CLOCK_LP_HASH = RCC_AHB2LPENR_HASHLPEN_Msk,
	#endif

	#if defined(RCC_AHB2LPENR_RNGLPEN_Msk)
		AJ_BUS_AHB2_CLOCK_LP_RNG = RCC_AHB2LPENR_RNGLPEN_Msk,
	#endif

	#if defined(RCC_AHB2LPENR_OTGFSLPEN_Msk)
		AJ_BUS_AHB2_CLOCK_LP_OTGFS = RCC_AHB2LPENR_OTGFSLPEN_Msk,
	#endif

	AJ_BUS_AHB2_CLOCK_LP_ALL = 0xFFFFFFFFU
} aj_bus_ahb2_clock_lp_mask_t;
#endif	/* RCC_AHB2_SUPPORT */


#if defined(RCC_AHB3_SUPPORT)
//********************************************************
typedef enum {
	#if defined(RCC_AHB3ENR_FSMCEN_Msk)
		AJ_BUS_AHB3_CLOCK_FSMC = RCC_AHB3ENR_FSMCEN_Msk,
	#endif

	#if defined(RCC_AHB3ENR_FMCEN_Msk)
		AJ_BUS_AHB3_CLOCK_FMC = RCC_AHB3ENR_FMCEN_Msk,
	#endif

	#if defined(RCC_AHB3ENR_QSPIEN_Msk)
		AJ_BUS_AHB3_CLOCK_QSPI = RCC_AHB3ENR_QSPIEN_Msk,
	#endif

	AJ_BUS_AHB3_CLOCK_ALL = 0xFFFFFFFFU
} aj_bus_ahb3_clock_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_AHB3RSTR_FSMCRST_Msk)
		AJ_BUS_AHB3_RESET_FSMC = RCC_AHB3RSTR_FSMCRST_Msk,
	#endif

	#if defined(RCC_AHB3RSTR_FMCRST_Msk)
		AJ_BUS_AHB3_RESET_FMC = RCC_AHB3RSTR_FMCRST_Msk,
	#endif

	#if defined(RCC_AHB3RSTR_QSPI RST_Msk)
		AJ_BUS_AHB3_RESET_QSPI = RCC_AHB3RSTR_QSPIRST_Msk,
	#endif

	AJ_BUS_AHB3_RESET_ALL = 0xFFFFFFFFU
} aj_bus_ahb3_reset_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_AHB3LPENR_FSMCLPEN_Msk)
		AJ_BUS_AHB3_CLOCK_LP_FSMC = RCC_AHB3LPENR_FSMCLPEN_Msk,
	#endif

	#if defined(RCC_AHB3LPENR_FMCLPEN_Msk)
		AJ_BUS_AHB3_CLOCK_LP_FMC = RCC_AHB3LPENR_FMCLPEN_Msk,
	#endif

	#if defined(RCC_AHB3LPENR_QSPILPEN_Msk)
		AJ_BUS_AHB3_CLOCK_LP_QSPI = RCC_AHB3LPENR_QSPILPEN_Msk,
	#endif

	AJ_BUS_AHB3_CLOCK_LP_ALL = 0xFFFFFFFFU
} aj_bus_ahb3_clock_lp_mask_t;

#endif	/* RCC_AHB3_SUPPORT */


//********************************************************
typedef enum {
	#if defined(RCC_APB1ENR_TIM2EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM2 = RCC_APB1ENR_TIM2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM3EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM3 = RCC_APB1ENR_TIM3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM4EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM4 = RCC_APB1ENR_TIM4EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM5EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM5 = RCC_APB1ENR_TIM5EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM6EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM6 = RCC_APB1ENR_TIM6EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM7EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM7 = RCC_APB1ENR_TIM7EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM12EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM12 = RCC_APB1ENR_TIM12EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM13EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM13 = RCC_APB1ENR_TIM13EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM14EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM14 = RCC_APB1ENR_TIM14EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_WWDGEN_Msk)
		AJ_BUS_APB1_CLOCK_WWDG = RCC_APB1ENR_WWDGEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_SPI2EN_Msk)
		AJ_BUS_APB1_CLOCK_SPI2 = RCC_APB1ENR_SPI2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_SPI3EN_Msk)
		AJ_BUS_APB1_CLOCK_SPI3 = RCC_APB1ENR_SPI3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USART2EN_Msk)
		AJ_BUS_APB1_CLOCK_USART2 = RCC_APB1ENR_USART2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USART3EN_Msk)
		AJ_BUS_APB1_CLOCK_USART3 = RCC_APB1ENR_USART3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_UART4EN_Msk)
		AJ_BUS_APB1_CLOCK_UART4 = RCC_APB1ENR_UART4EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_UART5EN_Msk)
		AJ_BUS_APB1_CLOCK_UART5 = RCC_APB1ENR_UART5EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_I2C1EN_Msk)
		AJ_BUS_APB1_CLOCK_I2C1 = RCC_APB1ENR_I2C1EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_I2C2EN_Msk)
		AJ_BUS_APB1_CLOCK_I2C2 = RCC_APB1ENR_I2C2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_I2C3EN_Msk)
		AJ_BUS_APB1_CLOCK_I2C3 = RCC_APB1ENR_I2C3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CAN1EN_Msk)
		AJ_BUS_APB1_CLOCK_CAN1 = RCC_APB1ENR_CAN1EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CAN2EN_Msk)
		AJ_BUS_APB1_CLOCK_CAN2 = RCC_APB1ENR_CAN2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_PWREN_Msk)
		AJ_BUS_APB1_CLOCK_PWR = RCC_APB1ENR_PWREN_Msk,
	#endif

	#if defined(RCC_APB1ENR_DACEN_Msk)
		AJ_BUS_APB1_CLOCK_DAC = RCC_APB1ENR_DACEN_Msk,
	#endif

	AJ_BUS_APB1_CLOCK_ALL = 0xFFFFFFFFU
} aj_bus_apb1_clock_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_APB1RSTR_TIM2RST_Msk)
		AJ_BUS_APB1_RESET_TIM2 = RCC_APB1RSTR_TIM2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM3RST_Msk)
		AJ_BUS_APB1_RESET_TIM3 = RCC_APB1RSTR_TIM3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM4RST_Msk)
		AJ_BUS_APB1_RESET_TIM4 = RCC_APB1RSTR_TIM4RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM5RST_Msk)
		AJ_BUS_APB1_RESET_TIM5 = RCC_APB1RSTR_TIM5RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM6RST_Msk)
		AJ_BUS_APB1_RESET_TIM6 = RCC_APB1RSTR_TIM6RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM7RST_Msk)
		AJ_BUS_APB1_RESET_TIM7 = RCC_APB1RSTR_TIM7RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM12RST_Msk)
		AJ_BUS_APB1_RESET_TIM12 = RCC_APB1RSTR_TIM12RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM13RST_Msk)
		AJ_BUS_APB1_RESET_TIM13 = RCC_APB1RSTR_TIM13RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM14RST_Msk)
		AJ_BUS_APB1_RESET_TIM14 = RCC_APB1RSTR_TIM14RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_WWDGRST_Msk)
		AJ_BUS_APB1_RESET_WWDG = RCC_APB1RSTR_WWDGRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_SPI2RST_Msk)
		AJ_BUS_APB1_RESET_SPI2 = RCC_APB1RSTR_SPI2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_SPI3RST_Msk)
		AJ_BUS_APB1_RESET_SPI3 = RCC_APB1RSTR_SPI3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USART2RST_Msk)
		AJ_BUS_APB1_RESET_USART2 = RCC_APB1RSTR_USART2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USART3RST_Msk)
		AJ_BUS_APB1_RESET_USART3 = RCC_APB1RSTR_USART3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_UART4RST_Msk)
		AJ_BUS_APB1_RESET_UART4 = RCC_APB1RSTR_UART4RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_UART5RST_Msk)
		AJ_BUS_APB1_RESET_UART5 = RCC_APB1RSTR_UART5RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_I2C1RST_Msk)
		AJ_BUS_APB1_RESET_I2C1 = RCC_APB1RSTR_I2C1RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_I2C2RST_Msk)
		AJ_BUS_APB1_RESET_I2C2 = RCC_APB1RSTR_I2C2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_I2C3RST_Msk)
		AJ_BUS_APB1_RESET_I2C3 = RCC_APB1RSTR_I2C3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CAN1RST_Msk)
		AJ_BUS_APB1_RESET_CAN1 = RCC_APB1RSTR_CAN1RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CAN2RST_Msk)
		AJ_BUS_APB1_RESET_CAN2 = RCC_APB1RSTR_CAN2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_PWRRST_Msk)
		AJ_BUS_APB1_RESET_PWR = RCC_APB1RSTR_PWRRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_DACRST_Msk)
		AJ_BUS_APB1_RESET_DAC = RCC_APB1RSTR_DACRST_Msk,
	#endif

	AJ_BUS_APB1_RESET_ALL = 0xFFFFFFFFU
} aj_bus_apb1_reset_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_APB1LPENR_TIM2LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM2 = RCC_APB1LPENR_TIM2LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM3LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM3 = RCC_APB1LPENR_TIM3LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM4LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM4 = RCC_APB1LPENR_TIM4LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM5LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM5 = RCC_APB1LPENR_TIM5LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM6LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM6 = RCC_APB1LPENR_TIM6LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM7LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM7 = RCC_APB1LPENR_TIM7LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM12LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM12 = RCC_APB1LPENR_TIM12LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM13LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM13 = RCC_APB1LPENR_TIM13LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_TIM14LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_TIM14 = RCC_APB1LPENR_TIM14LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_WWDGLPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_WWDG = RCC_APB1LPENR_WWDGLPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_SPI2LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_SPI2 = RCC_APB1LPENR_SPI2LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_SPI3LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_SPI3 = RCC_APB1LPENR_SPI3LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_USART2LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_USART2 = RCC_APB1LPENR_USART2LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_USART3LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_USART3 = RCC_APB1LPENR_USART3LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_UART4LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_UART4 = RCC_APB1LPENR_UART4LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_UART5LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_UART5 = RCC_APB1LPENR_UART5LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_I2C1LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_I2C1 = RCC_APB1LPENR_I2C1LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_I2C2LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_I2C2 = RCC_APB1LPENR_I2C2LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_I2C3LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_I2C3 = RCC_APB1LPENR_I2C3LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_CAN1LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_CAN1 = RCC_APB1LPENR_CAN1LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_CAN2LPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_CAN2 = RCC_APB1LPENR_CAN2LPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_PWRLPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_PWR = RCC_APB1LPENR_PWRLPEN_Msk,
	#endif

	#if defined(RCC_APB1LPENR_DACLPEN_Msk)
		AJ_BUS_APB1_CLOCK_LP_DAC = RCC_APB1LPENR_DACLPEN_Msk,
	#endif

	AJ_BUS_APB1_CLOCK_LP_ALL = 0xFFFFFFFFU
} aj_bus_apb1_clock_lp_mask_t;


//********************************************************
typedef enum {
	#if defined(RCC_APB2ENR_TIM1EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM1 = RCC_APB2ENR_TIM1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM8EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM8 = RCC_APB2ENR_TIM8EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_USART1EN_Msk)
		AJ_BUS_APB2_CLOCK_USART1 = RCC_APB2ENR_USART1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_USART6EN_Msk)
		AJ_BUS_APB2_CLOCK_USART6 = RCC_APB2ENR_USART6EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_ADC1EN_Msk)
		AJ_BUS_APB2_CLOCK_ADC1 = RCC_APB2ENR_ADC1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_ADC2EN_Msk)
		AJ_BUS_APB2_CLOCK_ADC2 = RCC_APB2ENR_ADC2EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_ADC3EN_Msk)
		AJ_BUS_APB2_CLOCK_ADC3 = RCC_APB2ENR_ADC3EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_SDIOEN_Msk)
		AJ_BUS_APB2_CLOCK_SDIO = RCC_APB2ENR_SDIOEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_SPI1EN_Msk)
		AJ_BUS_APB2_CLOCK_SPI1 = RCC_APB2ENR_SPI1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_SYSCFGEN_Msk)
		AJ_BUS_APB2_CLOCK_SYSCFG = RCC_APB2ENR_SYSCFGEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM9EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM9 = RCC_APB2ENR_TIM9EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM10EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM10 = RCC_APB2ENR_TIM10EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM11EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM11 = RCC_APB2ENR_TIM11EN_Msk,
	#endif

	AJ_BUS_APB2_CLOCK_ALL = 0xFFFFFFFFU
} aj_bus_apb2_clock_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_APB2RSTR_TIM1RST_Msk)
		AJ_BUS_APB2_RESET_TIM1 = RCC_APB2RSTR_TIM1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM8RST_Msk)
		AJ_BUS_APB2_RESET_TIM8 = RCC_APB2RSTR_TIM8RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_USART1RST_Msk)
		AJ_BUS_APB2_RESET_USART1 = RCC_APB2RSTR_USART1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_USART6RST_Msk)
		AJ_BUS_APB2_RESET_USART6 = RCC_APB2RSTR_USART6RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_ADCRST_Msk)
		AJ_BUS_APB2_RESET_ADC = RCC_APB2RSTR_ADCRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_SDIORST_Msk)
		AJ_BUS_APB2_RESET_SDIO = RCC_APB2RSTR_SDIORST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_SPI1RST_Msk)
		AJ_BUS_APB2_RESET_SPI1 = RCC_APB2RSTR_SPI1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_SYSCFGRST_Msk)
		AJ_BUS_APB2_RESET_SYSCFG = RCC_APB2RSTR_SYSCFGRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM9RST_Msk)
		AJ_BUS_APB2_RESET_TIM9 = RCC_APB2RSTR_TIM9RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM10RST_Msk)
		AJ_BUS_APB2_RESET_TIM10 = RCC_APB2RSTR_TIM10RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM11RST_Msk)
		AJ_BUS_APB2_RESET_TIM11 = RCC_APB2RSTR_TIM11RST_Msk,
	#endif

	AJ_BUS_APB2_RESET_ALL = 0xFFFFFFFFU
} aj_bus_apb2_reset_mask_t;

//********************************************************
typedef enum {
	#if defined(RCC_APB2LPENR_TIM1LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_TIM1 = RCC_APB2LPENR_TIM1LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_TIM8LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_TIM8 = RCC_APB2LPENR_TIM8LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_USART1LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_USART1 = RCC_APB2LPENR_USART1LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_USART6LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_USART6 = RCC_APB2LPENR_USART6LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_ADC1LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_ADC1 = RCC_APB2LPENR_ADC1LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_ADC2LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_ADC2 = RCC_APB2LPENR_ADC2LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_ADC3LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_ADC3 = RCC_APB2LPENR_ADC3LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_SDIOLPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_SDIO = RCC_APB2LPENR_SDIOLPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_SPI1LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_SPI1 = RCC_APB2LPENR_SPI1LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_SYSCFGLPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_SYSCFG = RCC_APB2LPENR_SYSCFGLPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_TIM9LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_TIM9 = RCC_APB2LPENR_TIM9LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_TIM10LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_TIM10 = RCC_APB2LPENR_TIM10LPEN_Msk,
	#endif

	#if defined(RCC_APB2LPENR_TIM11LPEN_Msk)
		AJ_BUS_APB2_CLOCK_LP_TIM11 = RCC_APB2LPENR_TIM11LPEN_Msk,
	#endif

	AJ_BUS_APB2_CLOCK_LP_ALL = 0xFFFFFFFFU
} aj_bus_apb2_clock_lp_mask_t;


#ifdef __cplusplus
}
#endif

#endif  /* AJ_BUS_TYPE_INCLUDED */