#ifndef AJ_BUS_TYPE_INCLUDED
#define AJ_BUS_TYPE_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


#include <stm32f1xx.h>

typedef enum {
	#if defined(RCC_AHBENR_DMA1EN_Msk)
		AJ_BUS_CLOCK_AHB_DMA1 = RCC_AHBENR_DMA1EN_Msk,
	#endif

	#if defined(RCC_AHBENR_DMA2EN_Msk)
		AJ_BUS_CLOCK_AHB_DMA2 = RCC_AHBENR_DMA2EN_Msk,
	#endif

	#if defined(RCC_AHBENR_SRAMEN_Msk)
		AJ_BUS_CLOCK_AHB_SRAM = RCC_AHBENR_SRAMEN_Msk,
	#endif

	#if defined(RCC_AHBENR_FLITFEN_Msk)
		AJ_BUS_CLOCK_AHB_FLITF = RCC_AHBENR_FLITFEN_Msk,
	#endif

	#if defined(RCC_AHBENR_CRCEN_Msk)
		AJ_BUS_CLOCK_AHB_CRC = RCC_AHBENR_CRCEN_Msk,
	#endif

	#if defined(RCC_AHBENR_OTGFSEN_Msk)
		AJ_BUS_CLOCK_AHB_OTGFS = RCC_AHBENR_OTGFSEN_Msk,
	#endif

	#if defined(RCC_AHBENR_ETHMACEN_Msk)
		AJ_BUS_CLOCK_AHB_ETHMAC = RCC_AHBENR_ETHMACEN_Msk,
	#endif

	#if defined(RCC_AHBENR_ETHMACTXEN_Msk)
		AJ_BUS_CLOCK_AHB_ETHMACTX = RCC_AHBENR_ETHMACTXEN_Msk,
	#endif

	#if defined(RCC_AHBENR_ETHMACRXEN_Msk)
		AJ_BUS_CLOCK_AHB_ETHMACRX = RCC_AHBENR_ETHMACRXEN_Msk,
	#endif

	#if defined(RCC_AHBENR_FSMCEN_Msk)
		AJ_BUS_CLOCK_AHB_FSMC = RCC_AHBENR_FSMCEN_Msk,
	#endif

	#if defined(RCC_AHBENR_SDIOEN_Msk)
		AJ_BUS_CLOCK_AHB_SDIO = RCC_AHBENR_SDIOEN_Msk,
	#endif
	
	AJ_BUS_CLOCK_AHB_ALL = 0xFFFFFFFFU	
} aj_bus_clock_ahb_mask_t;

typedef enum {
	#if defined(RCC_AHBRSTR_OTGFSRST_Msk)
		AJ_BUS_RESET_AHB_OTGFS = RCC_AHBRSTR_OTGFSRST_Msk,
	#endif

	#if defined(RCC_AHBRSTR_ETHMACRST_Msk)
		AJ_BUS_RESET_AHB_ETHMAC = RCC_AHBRSTR_ETHMACRST_Msk,
	#endif
	
	AJ_BUS_RESET_AHB_ALL = 0xFFFFFFFFU	
} aj_bus_reset_ahb_mask_t;


typedef enum {
	#if defined(RCC_APB1ENR_TIM2EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM2 = RCC_APB1ENR_TIM2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM3EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM3 = RCC_APB1ENR_TIM3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM4EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM4 = RCC_APB1ENR_TIM4EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM5EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM5 = RCC_APB1ENR_TIM5EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM6EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM6 = RCC_APB1ENR_TIM6EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM7EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM7 = RCC_APB1ENR_TIM7EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM12EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM12 = RCC_APB1ENR_TIM12EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM13EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM13 = RCC_APB1ENR_TIM13EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM14EN_Msk)
		AJ_BUS_CLOCK_APB1_TIM14 = RCC_APB1ENR_TIM14EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_WWDGEN_Msk)
		AJ_BUS_CLOCK_APB1_WWDG = RCC_APB1ENR_WWDGEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_SPI2EN_Msk)
		AJ_BUS_CLOCK_APB1_SPI2 = RCC_APB1ENR_SPI2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_SPI3EN_Msk)
		AJ_BUS_CLOCK_APB1_SPI3 = RCC_APB1ENR_SPI3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USART2EN_Msk)
		AJ_BUS_CLOCK_APB1_USART2 = RCC_APB1ENR_USART2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USART3EN_Msk)
		AJ_BUS_CLOCK_APB1_USART3 = RCC_APB1ENR_USART3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_UART4EN_Msk)
		AJ_BUS_CLOCK_APB1_UART4 = RCC_APB1ENR_UART4EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_UART5EN_Msk)
		AJ_BUS_CLOCK_APB1_UART5 = RCC_APB1ENR_UART5EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_I2C1EN_Msk)
		AJ_BUS_CLOCK_APB1_I2C1 = RCC_APB1ENR_I2C1EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_I2C2EN_Msk)
		AJ_BUS_CLOCK_APB1_I2C2 = RCC_APB1ENR_I2C2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USBEN_Msk)
		AJ_BUS_CLOCK_APB1_USB = RCC_APB1ENR_USBEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CAN1EN_Msk)
		AJ_BUS_CLOCK_APB1_CAN1 = RCC_APB1ENR_CAN1EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CAN2EN_Msk)
		AJ_BUS_CLOCK_APB1_CAN2 = RCC_APB1ENR_CAN2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_BKPEN_Msk)
		AJ_BUS_CLOCK_APB1_BKP = RCC_APB1ENR_BKPEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_PWREN_Msk)
		AJ_BUS_CLOCK_APB1_PWR = RCC_APB1ENR_PWREN_Msk,
	#endif

	#if defined(RCC_APB1ENR_DACEN_Msk)
		AJ_BUS_CLOCK_APB1_DAC = RCC_APB1ENR_DACEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CECEN_Msk)
		AJ_BUS_CLOCK_APB1_CEC = RCC_APB1ENR_CECEN_Msk,
	#endif

	AJ_BUS_CLOCK_APB1_ALL = 0xFFFFFFFFU
} aj_bus_clock_apb1_mask_t;

typedef enum {
	#if defined(RCC_APB1RSTR_TIM2RST_Msk)
		AJ_BUS_RESET_APB1_TIM2 = RCC_APB1RSTR_TIM2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM3RST_Msk)
		AJ_BUS_RESET_APB1_TIM3 = RCC_APB1RSTR_TIM3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM4RST_Msk)
		AJ_BUS_RESET_APB1_TIM4 = RCC_APB1RSTR_TIM4RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM5RST_Msk)
		AJ_BUS_RESET_APB1_TIM5 = RCC_APB1RSTR_TIM5RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM6RST_Msk)
		AJ_BUS_RESET_APB1_TIM6 = RCC_APB1RSTR_TIM6RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM7RST_Msk)
		AJ_BUS_RESET_APB1_TIM7 = RCC_APB1RSTR_TIM7RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM12RST_Msk)
		AJ_BUS_RESET_APB1_TIM12 = RCC_APB1RSTR_TIM12RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM13RST_Msk)
		AJ_BUS_RESET_APB1_TIM13 = RCC_APB1RSTR_TIM13RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM14RST_Msk)
		AJ_BUS_RESET_APB1_TIM14 = RCC_APB1RSTR_TIM14RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_WWDGRST_Msk)
		AJ_BUS_RESET_APB1_WWDG = RCC_APB1RSTR_WWDGRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_SPI2RST_Msk)
		AJ_BUS_RESET_APB1_SPI2 = RCC_APB1RSTR_SPI2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_SPI3RST_Msk)
		AJ_BUS_RESET_APB1_SPI3 = RCC_APB1RSTR_SPI3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USART2RST_Msk)
		AJ_BUS_RESET_APB1_USART2 = RCC_APB1RSTR_USART2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USART3RST_Msk)
		AJ_BUS_RESET_APB1_USART3 = RCC_APB1RSTR_USART3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_UART4RST_Msk)
		AJ_BUS_RESET_APB1_UART4 = RCC_APB1RSTR_UART4RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_UART5RST_Msk)
		AJ_BUS_RESET_APB1_UART5 = RCC_APB1RSTR_UART5RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_I2C1RST_Msk)
		AJ_BUS_RESET_APB1_I2C1 = RCC_APB1RSTR_I2C1RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_I2C2RST_Msk)
		AJ_BUS_RESET_APB1_I2C2 = RCC_APB1RSTR_I2C2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USBRST_Msk)
		AJ_BUS_RESET_APB1_USB = RCC_APB1RSTR_USBRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CAN1RST_Msk)
		AJ_BUS_RESET_APB1_CAN1 = RCC_APB1RSTR_CAN1RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CAN2RST_Msk)
		AJ_BUS_RESET_APB1_CAN2 = RCC_APB1RSTR_CAN2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_BKPRST_Msk)
		AJ_BUS_RESET_APB1_BKP = RCC_APB1RSTR_BKPRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_PWRRST_Msk)
		AJ_BUS_RESET_APB1_PWR = RCC_APB1RSTR_PWRRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_DACRST_Msk)
		AJ_BUS_RESET_APB1_DAC = RCC_APB1RSTR_DACRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CECRST_Msk)
		AJ_BUS_RESET_APB1_CEC = RCC_APB1RSTR_CECRST_Msk,
	#endif

	AJ_BUS_RESET_APB1_ALL = 0xFFFFFFFFU
} aj_bus_reset_apb1_mask_t;


typedef enum {
	#if defined(RCC_APB2ENR_AFIOEN_Msk)
		AJ_BUS_CLOCK_APB2_AFIO = RCC_APB2ENR_AFIOEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPAEN_Msk)
		AJ_BUS_CLOCK_APB2_GPIOA = RCC_APB2ENR_IOPAEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPBEN_Msk)
		AJ_BUS_CLOCK_APB2_GPIOB = RCC_APB2ENR_IOPBEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPCEN_Msk)
		AJ_BUS_CLOCK_APB2_GPIOC = RCC_APB2ENR_IOPCEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPDEN_Msk)
		AJ_BUS_CLOCK_APB2_GPIOD = RCC_APB2ENR_IOPDEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPEEN_Msk)
		AJ_BUS_CLOCK_APB2_GPIOE = RCC_APB2ENR_IOPEEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPFEN_Msk)
		AJ_BUS_CLOCK_APB2_GPIOF = RCC_APB2ENR_IOPFEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPGEN_Msk)
		AJ_BUS_CLOCK_APB2_GPIOG = RCC_APB2ENR_IOPGEN_Msk,
	#endif
	
	#if defined(RCC_APB2ENR_ADC1EN_Msk)
		AJ_BUS_CLOCK_APB2_ADC1 = RCC_APB2ENR_ADC1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_ADC2EN_Msk)
		AJ_BUS_CLOCK_APB2_ADC2 = RCC_APB2ENR_ADC2EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_ADC3EN_Msk)
		AJ_BUS_CLOCK_APB2_ADC3 = RCC_APB2ENR_ADC3EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM1EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM1 = RCC_APB2ENR_TIM1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM8EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM8  = RCC_APB2ENR_TIM8EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM9EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM9  = RCC_APB2ENR_TIM9EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM10EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM10 = RCC_APB2ENR_TIM10EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM11EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM11 = RCC_APB2ENR_TIM11EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM15EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM15 = RCC_APB2ENR_TIM15EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM16EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM16 = RCC_APB2ENR_TIM16EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM17EN_Msk)
		AJ_BUS_CLOCK_APB2_TIM17 = RCC_APB2ENR_TIM17EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_SPI1EN_Msk)
		AJ_BUS_CLOCK_APB2_SPI1 = RCC_APB2ENR_SPI1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_USART1EN_Msk)
		AJ_BUS_CLOCK_APB2_USART1 = RCC_APB2ENR_USART1EN_Msk,
	#endif

	AJ_BUS_CLOCK_APB2_ALL = 0xFFFFFFFFU
} aj_bus_clock_apb2_mask_t;

typedef enum {
	#if defined(RCC_APB2RSTR_AFIORST_Msk)
		AJ_BUS_RESET_APB2_AFIO = RCC_APB2RSTR_AFIORST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPARST_Msk)
		AJ_BUS_RESET_APB2_GPIOA = RCC_APB2RSTR_IOPARST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPBRST_Msk)
		AJ_BUS_RESET_APB2_GPIOB = RCC_APB2RSTR_IOPBRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPCRST_Msk)
		AJ_BUS_RESET_APB2_GPIOC = RCC_APB2RSTR_IOPCRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPDRST_Msk)
		AJ_BUS_RESET_APB2_GPIOD = RCC_APB2RSTR_IOPDRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPERST_Msk)
		AJ_BUS_RESET_APB2_GPIOE = RCC_APB2RSTR_IOPERST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPFRST_Msk)
		AJ_BUS_RESET_APB2_GPIOF = RCC_APB2RSTR_IOPFRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPGRST_Msk)
		AJ_BUS_RESET_APB2_GPIOG = RCC_APB2RSTR_IOPGRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_ADC1RST_Msk)
		AJ_BUS_RESET_APB2_ADC1 = RCC_APB2RSTR_ADC1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_ADC2RST_Msk)
		AJ_BUS_RESET_APB2_ADC2 = RCC_APB2RSTR_ADC2RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_ADC3RST_Msk)
		AJ_BUS_RESET_APB2_ADC3 = RCC_APB2RSTR_ADC3RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM1RST_Msk)
		AJ_BUS_RESET_APB2_TIM1 = RCC_APB2RSTR_TIM1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM8RST_Msk)
		AJ_BUS_RESET_APB2_TIM8 = RCC_APB2RSTR_TIM8RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM9RST_Msk)
		AJ_BUS_RESET_APB2_TIM9 = RCC_APB2RSTR_TIM9RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM10RST_Msk)
		AJ_BUS_RESET_APB2_TIM10 = RCC_APB2RSTR_TIM10RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM11RST_Msk)
		AJ_BUS_RESET_APB2_TIM11 = RCC_APB2RSTR_TIM11RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM15RST_Msk)
		AJ_BUS_RESET_APB2_TIM15 = RCC_APB2RSTR_TIM15RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM16RST_Msk)
		AJ_BUS_RESET_APB2_TIM16 = RCC_APB2RSTR_TIM16RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM17RST_Msk)
		AJ_BUS_RESET_APB2_TIM17 = RCC_APB2RSTR_TIM17RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_SPI1RST_Msk)
		AJ_BUS_RESET_APB2_SPI1 = RCC_APB2RSTR_SPI1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_USART1RST_Msk)
		AJ_BUS_RESET_APB2_USART1 = RCC_APB2RSTR_USART1RST_Msk,
	#endif

	AJ_BUS_RESET_APB2_ALL = 0xFFFFFFFFU
} aj_bus_reset_apb2_mask_t;



#ifdef __cplusplus
}
#endif

#endif  /* AJ_BUS_TYPE_INCLUDED */
