#ifndef AJ_BUS_TYPE_INCLUDED
#define AJ_BUS_TYPE_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


#include <stm32f1xx.h>

typedef enum {
	AJ_BUS_CLOCK_DISABLE = 0U,
	AJ_BUS_CLOCK_ENABLE  = 1U
} aj_bus_clock_state_t;

typedef enum {
	#if defined(RCC_AHBENR_DMA1EN_Msk)
		AJ_BUS_AHB_CLOCK_DMA1 = RCC_AHBENR_DMA1EN_Msk,
	#endif

	#if defined(RCC_AHBENR_DMA2EN_Msk)
		AJ_BUS_AHB_CLOCK_DMA2 = RCC_AHBENR_DMA2EN_Msk,
	#endif

	#if defined(RCC_AHBENR_SRAMEN_Msk)
		AJ_BUS_AHB_CLOCK_SRAM = RCC_AHBENR_SRAMEN_Msk,
	#endif

	#if defined(RCC_AHBENR_FLITFEN_Msk)
		AJ_BUS_AHB_CLOCK_FLITF = RCC_AHBENR_FLITFEN_Msk,
	#endif

	#if defined(RCC_AHBENR_CRCEN_Msk)
		AJ_BUS_AHB_CLOCK_CRC = RCC_AHBENR_CRCEN_Msk,
	#endif

	#if defined(RCC_AHBENR_OTGFSEN_Msk)
		AJ_BUS_AHB_CLOCK_OTGFS = RCC_AHBENR_OTGFSEN_Msk,
	#endif

	#if defined(RCC_AHBENR_ETHMACEN_Msk)
		AJ_BUS_AHB_CLOCK_ETHMAC = RCC_AHBENR_ETHMACEN_Msk,
	#endif

	#if defined(RCC_AHBENR_ETHMACTXEN_Msk)
		AJ_BUS_AHB_CLOCK_ETHMACTX = RCC_AHBENR_ETHMACTXEN_Msk,
	#endif

	#if defined(RCC_AHBENR_ETHMACRXEN_Msk)
		AJ_BUS_AHB_CLOCK_ETHMACRX = RCC_AHBENR_ETHMACRXEN_Msk,
	#endif

	#if defined(RCC_AHBENR_FSMCEN_Msk)
		AJ_BUS_AHB_CLOCK_FSMC = RCC_AHBENR_FSMCEN_Msk,
	#endif

	#if defined(RCC_AHBENR_SDIOEN_Msk)
		AJ_BUS_AHB_CLOCK_SDIO = RCC_AHBENR_SDIOEN_Msk,
	#endif
	
	AJ_BUS_AHB_CLOCK_ALL = 0xFFFFFFFFU	
} aj_bus_ahb_clock_mask_t;

typedef enum {
	#if defined(RCC_AHBRSTR_OTGFSRST_Msk)
		AJ_BUS_AHB_RESET_OTGFS = RCC_AHBRSTR_OTGFSRST_Msk,
	#endif

	#if defined(RCC_AHBRSTR_ETHMACRST_Msk)
		AJ_BUS_AHB_RESET_ETHMAC = RCC_AHBRSTR_ETHMACRST_Msk,
	#endif
	
	AJ_BUS_AHB_RESET_ALL = 0xFFFFFFFFU	
} aj_bus_ahb_reset_mask_t;


typedef enum {
	#if defined(RCC_APB1ENR_TIM2EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM2 = RCC_APB1ENR_TIM2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM3EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM3 = RCC_APB1ENR_TIM3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM4EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM4 = RCC_APB1ENR_TIM4EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM5EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM5 = RCC_APB1ENR_TIM5EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM6EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM6 = RCC_APB1ENR_TIM6EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM7EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM7 = RCC_APB1ENR_TIM7EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM12EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM12 = RCC_APB1ENR_TIM12EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM13EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM13 = RCC_APB1ENR_TIM13EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_TIM14EN_Msk)
		AJ_BUS_APB1_CLOCK_TIM14 = RCC_APB1ENR_TIM14EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_WWDGEN_Msk)
		AJ_BUS_APB1_CLOCK_WWDG = RCC_APB1ENR_WWDGEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_SPI2EN_Msk)
		AJ_BUS_APB1_CLOCK_SPI2 = RCC_APB1ENR_SPI2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_SPI3EN_Msk)
		AJ_BUS_APB1_CLOCK_SPI3 = RCC_APB1ENR_SPI3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USART2EN_Msk)
		AJ_BUS_APB1_CLOCK_USART2 = RCC_APB1ENR_USART2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USART3EN_Msk)
		AJ_BUS_APB1_CLOCK_USART3 = RCC_APB1ENR_USART3EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_UART4EN_Msk)
		AJ_BUS_APB1_CLOCK_UART4 = RCC_APB1ENR_UART4EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_UART5EN_Msk)
		AJ_BUS_APB1_CLOCK_UART5 = RCC_APB1ENR_UART5EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_I2C1EN_Msk)
		AJ_BUS_APB1_CLOCK_I2C1 = RCC_APB1ENR_I2C1EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_I2C2EN_Msk)
		AJ_BUS_APB1_CLOCK_I2C2 = RCC_APB1ENR_I2C2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_USBEN_Msk)
		AJ_BUS_APB1_CLOCK_USB = RCC_APB1ENR_USBEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CAN1EN_Msk)
		AJ_BUS_APB1_CLOCK_CAN1 = RCC_APB1ENR_CAN1EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CAN2EN_Msk)
		AJ_BUS_APB1_CLOCK_CAN2 = RCC_APB1ENR_CAN2EN_Msk,
	#endif

	#if defined(RCC_APB1ENR_BKPEN_Msk)
		AJ_BUS_APB1_CLOCK_BKP = RCC_APB1ENR_BKPEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_PWREN_Msk)
		AJ_BUS_APB1_CLOCK_PWR = RCC_APB1ENR_PWREN_Msk,
	#endif

	#if defined(RCC_APB1ENR_DACEN_Msk)
		AJ_BUS_APB1_CLOCK_DAC = RCC_APB1ENR_DACEN_Msk,
	#endif

	#if defined(RCC_APB1ENR_CECEN_Msk)
		AJ_BUS_APB1_CLOCK_CEC = RCC_APB1ENR_CECEN_Msk,
	#endif

	AJ_BUS_APB1_CLOCK_ALL = 0xFFFFFFFFU
} aj_bus_apb1_clock_mask_t;

typedef enum {
	#if defined(RCC_APB1RSTR_TIM2RST_Msk)
		AJ_BUS_APB1_RESET_TIM2 = RCC_APB1RSTR_TIM2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM3RST_Msk)
		AJ_BUS_APB1_RESET_TIM3 = RCC_APB1RSTR_TIM3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM4RST_Msk)
		AJ_BUS_APB1_RESET_TIM4 = RCC_APB1RSTR_TIM4RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM5RST_Msk)
		AJ_BUS_APB1_RESET_TIM5 = RCC_APB1RSTR_TIM5RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM6RST_Msk)
		AJ_BUS_APB1_RESET_TIM6 = RCC_APB1RSTR_TIM6RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM7RST_Msk)
		AJ_BUS_APB1_RESET_TIM7 = RCC_APB1RSTR_TIM7RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM12RST_Msk)
		AJ_BUS_APB1_RESET_TIM12 = RCC_APB1RSTR_TIM12RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM13RST_Msk)
		AJ_BUS_APB1_RESET_TIM13 = RCC_APB1RSTR_TIM13RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_TIM14RST_Msk)
		AJ_BUS_APB1_RESET_TIM14 = RCC_APB1RSTR_TIM14RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_WWDGRST_Msk)
		AJ_BUS_APB1_RESET_WWDG = RCC_APB1RSTR_WWDGRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_SPI2RST_Msk)
		AJ_BUS_APB1_RESET_SPI2 = RCC_APB1RSTR_SPI2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_SPI3RST_Msk)
		AJ_BUS_APB1_RESET_SPI3 = RCC_APB1RSTR_SPI3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USART2RST_Msk)
		AJ_BUS_APB1_RESET_USART2 = RCC_APB1RSTR_USART2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USART3RST_Msk)
		AJ_BUS_APB1_RESET_USART3 = RCC_APB1RSTR_USART3RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_UART4RST_Msk)
		AJ_BUS_APB1_RESET_UART4 = RCC_APB1RSTR_UART4RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_UART5RST_Msk)
		AJ_BUS_APB1_RESET_UART5 = RCC_APB1RSTR_UART5RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_I2C1RST_Msk)
		AJ_BUS_APB1_RESET_I2C1 = RCC_APB1RSTR_I2C1RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_I2C2RST_Msk)
		AJ_BUS_APB1_RESET_I2C2 = RCC_APB1RSTR_I2C2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_USBRST_Msk)
		AJ_BUS_APB1_RESET_USB = RCC_APB1RSTR_USBRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CAN1RST_Msk)
		AJ_BUS_APB1_RESET_CAN1 = RCC_APB1RSTR_CAN1RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CAN2RST_Msk)
		AJ_BUS_APB1_RESET_CAN2 = RCC_APB1RSTR_CAN2RST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_BKPRST_Msk)
		AJ_BUS_APB1_RESET_BKP = RCC_APB1RSTR_BKPRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_PWRRST_Msk)
		AJ_BUS_APB1_RESET_PWR = RCC_APB1RSTR_PWRRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_DACRST_Msk)
		AJ_BUS_APB1_RESET_DAC = RCC_APB1RSTR_DACRST_Msk,
	#endif

	#if defined(RCC_APB1RSTR_CECRST_Msk)
		AJ_BUS_APB1_RESET_CEC = RCC_APB1RSTR_CECRST_Msk,
	#endif

	AJ_BUS_APB1_RESET_ALL = 0xFFFFFFFFU
} aj_bus_apb1_reset_mask_t;


typedef enum {
	#if defined(RCC_APB2ENR_AFIOEN_Msk)
		AJ_BUS_APB2_CLOCK_AFIO = RCC_APB2ENR_AFIOEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPAEN_Msk)
		AJ_BUS_APB2_CLOCK_GPIOA = RCC_APB2ENR_IOPAEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPBEN_Msk)
		AJ_BUS_APB2_CLOCK_GPIOB = RCC_APB2ENR_IOPBEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPCEN_Msk)
		AJ_BUS_APB2_CLOCK_GPIOC = RCC_APB2ENR_IOPCEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPDEN_Msk)
		AJ_BUS_APB2_CLOCK_GPIOD = RCC_APB2ENR_IOPDEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPEEN_Msk)
		AJ_BUS_APB2_CLOCK_GPIOE = RCC_APB2ENR_IOPEEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPFEN_Msk)
		AJ_BUS_APB2_CLOCK_GPIOF = RCC_APB2ENR_IOPFEN_Msk,
	#endif

	#if defined(RCC_APB2ENR_IOPGEN_Msk)
		AJ_BUS_APB2_CLOCK_GPIOG = RCC_APB2ENR_IOPGEN_Msk,
	#endif
	
	#if defined(RCC_APB2ENR_ADC1EN_Msk)
		AJ_BUS_APB2_CLOCK_ADC1 = RCC_APB2ENR_ADC1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_ADC2EN_Msk)
		AJ_BUS_APB2_CLOCK_ADC2 = RCC_APB2ENR_ADC2EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_ADC3EN_Msk)
		AJ_BUS_APB2_CLOCK_ADC3 = RCC_APB2ENR_ADC3EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM1EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM1 = RCC_APB2ENR_TIM1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM8EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM8  = RCC_APB2ENR_TIM8EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM9EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM9  = RCC_APB2ENR_TIM9EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM10EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM10 = RCC_APB2ENR_TIM10EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM11EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM11 = RCC_APB2ENR_TIM11EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM15EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM15 = RCC_APB2ENR_TIM15EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM16EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM16 = RCC_APB2ENR_TIM16EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_TIM17EN_Msk)
		AJ_BUS_APB2_CLOCK_TIM17 = RCC_APB2ENR_TIM17EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_SPI1EN_Msk)
		AJ_BUS_APB2_CLOCK_SPI1 = RCC_APB2ENR_SPI1EN_Msk,
	#endif

	#if defined(RCC_APB2ENR_USART1EN_Msk)
		AJ_BUS_APB2_CLOCK_USART1 = RCC_APB2ENR_USART1EN_Msk,
	#endif

	AJ_BUS_APB2_CLOCK_ALL = 0xFFFFFFFFU
} aj_bus_apb2_clock_mask_t;

typedef enum {
	#if defined(RCC_APB2RSTR_AFIORST_Msk)
		AJ_BUS_APB2_RESET_AFIO = RCC_APB2RSTR_AFIORST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPARST_Msk)
		AJ_BUS_APB2_RESET_GPIOA = RCC_APB2RSTR_IOPARST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPBRST_Msk)
		AJ_BUS_APB2_RESET_GPIOB = RCC_APB2RSTR_IOPBRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPCRST_Msk)
		AJ_BUS_APB2_RESET_GPIOC = RCC_APB2RSTR_IOPCRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPDRST_Msk)
		AJ_BUS_APB2_RESET_GPIOD = RCC_APB2RSTR_IOPDRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPERST_Msk)
		AJ_BUS_APB2_RESET_GPIOE = RCC_APB2RSTR_IOPERST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPFRST_Msk)
		AJ_BUS_APB2_RESET_GPIOF = RCC_APB2RSTR_IOPFRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_IOPGRST_Msk)
		AJ_BUS_APB2_RESET_GPIOG = RCC_APB2RSTR_IOPGRST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_ADC1RST_Msk)
		AJ_BUS_APB2_RESET_ADC1 = RCC_APB2RSTR_ADC1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_ADC2RST_Msk)
		AJ_BUS_APB2_RESET_ADC2 = RCC_APB2RSTR_ADC2RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_ADC3RST_Msk)
		AJ_BUS_APB2_RESET_ADC3 = RCC_APB2RSTR_ADC3RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM1RST_Msk)
		AJ_BUS_APB2_RESET_TIM1 = RCC_APB2RSTR_TIM1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM8RST_Msk)
		AJ_BUS_APB2_RESET_TIM8 = RCC_APB2RSTR_TIM8RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM9RST_Msk)
		AJ_BUS_APB2_RESET_TIM9 = RCC_APB2RSTR_TIM9RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM10RST_Msk)
		AJ_BUS_APB2_RESET_TIM10 = RCC_APB2RSTR_TIM10RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM11RST_Msk)
		AJ_BUS_APB2_RESET_TIM11 = RCC_APB2RSTR_TIM11RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM15RST_Msk)
		AJ_BUS_APB2_RESET_TIM15 = RCC_APB2RSTR_TIM15RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM16RST_Msk)
		AJ_BUS_APB2_RESET_TIM16 = RCC_APB2RSTR_TIM16RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_TIM17RST_Msk)
		AJ_BUS_APB2_RESET_TIM17 = RCC_APB2RSTR_TIM17RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_SPI1RST_Msk)
		AJ_BUS_APB2_RESET_SPI1 = RCC_APB2RSTR_SPI1RST_Msk,
	#endif

	#if defined(RCC_APB2RSTR_USART1RST_Msk)
		AJ_BUS_APB2_RESET_USART1 = RCC_APB2RSTR_USART1RST_Msk,
	#endif

	AJ_BUS_APB2_RESET_ALL = 0xFFFFFFFFU
} aj_bus_apb2_reset_mask_t;



#ifdef __cplusplus
}
#endif

#endif  /* AJ_BUS_TYPE_INCLUDED */
